"""
Fetches South African public holidays from the Nager.Date public API and outputs
a JavaScript file ready to drop into src/data/publicHolidays.js

No API key required. Source: https://date.nager.at/api/v3/PublicHolidays/{year}/ZA

Usage:
    python3 scripts/scrape_public_holidays.py --year 2025
    python3 scripts/scrape_public_holidays.py --year 2025 --year 2026

Requires: pip install requests
"""

import argparse
import sys
from datetime import datetime

import requests

# date.nager.at is a free, open public holiday API — no key, no rate limits for light use
API_URL = "https://date.nager.at/api/v3/PublicHolidays/{year}/ZA"

# Only keep "Public" type holidays — the API also returns "Optional" (e.g. some observances)
INCLUDE_TYPES = {"Public"}


def fetch_year(year: int) -> list[dict]:
    url = API_URL.format(year=year)
    print(f"Fetching: {url}")

    response = requests.get(url, timeout=10)
    response.raise_for_status()

    holidays = []
    for item in response.json():
        # "types" is a list — keep only entries that include "Public"
        if not any(t in INCLUDE_TYPES for t in item.get("types", [])):
            continue

        date_str = item["date"]  # already "YYYY-MM-DD"
        name = item["localName"]  # local SA name

        holidays.append({"date": date_str, "name": name})
        print(f"  Found: {date_str} — {name}")

    return holidays


def to_js(all_holidays: dict[int, list[dict]]) -> str:
    """Render the scraped data as a JavaScript module."""
    lines = [
        "// South African public holidays — auto-generated by scripts/scrape_public_holidays.py",
        "// Source: https://date.nager.at/api/v3/PublicHolidays/{year}/ZA",
        "",
        "export const PUBLIC_HOLIDAYS = {",
    ]

    for year, holidays in sorted(all_holidays.items()):
        lines.append(f"  {year}: [")
        for h in holidays:
            lines.append(f"    {{ date: '{h['date']}', name: \"{h['name']}\" }},")
        lines.append("  ],")

    lines += [
        "}",
        "",
        "export function getPublicHolidaysForYear(year) {",
        "  return PUBLIC_HOLIDAYS[year] ?? []",
        "}",
        "",
        "export function isPublicHoliday(dateStr, year) {",
        "  return getPublicHolidaysForYear(year).some((h) => h.date === dateStr)",
        "}",
        "",
        "export function getHolidayName(dateStr, year) {",
        "  return getPublicHolidaysForYear(year).find((h) => h.date === dateStr)?.name ?? null",
        "}",
        "",
    ]

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Scrape SA public holidays")
    parser.add_argument(
        "--year",
        type=int,
        action="append",
        default=[],
        help="Year(s) to scrape (can be passed multiple times)",
    )
    parser.add_argument(
        "--output",
        default="web/src/data/publicHolidays.js",
        help="Output JS file path (default: web/src/data/publicHolidays.js)",
    )
    args = parser.parse_args()

    years = args.year or [datetime.now().year, datetime.now().year + 1]

    all_holidays = {}
    for year in years:
        all_holidays[year] = fetch_year(year)

    js_content = to_js(all_holidays)

    with open(args.output, "w") as f:
        f.write(js_content)

    total = sum(len(v) for v in all_holidays.values())
    print(f"\nDone — {total} holidays written to {args.output}")


if __name__ == "__main__":
    main()
