"""
Scrapes South African school holidays from schoolholidays.co.za and outputs
a JavaScript file ready to drop into src/data/schoolHolidays.js

Usage:
    python scripts/scrape_school_holidays.py --year 2025

Requires: pip install requests beautifulsoup4
"""

import argparse
import re
import sys
from datetime import datetime, timedelta

import requests
from bs4 import BeautifulSoup

# schoolholidays.co.za has per-province pages with clean HTML tables
# NOTE: Update this URL if a better structured source is found.
# The DBE publishes official calendars at https://www.education.gov.za but mostly as PDFs.
# publicholidays.co.za has province pages with readable HTML — try this if schoolholidays.co.za fails.
BASE_URL = "https://www.publicholidays.co.za/south-africa/school-holidays/{year}/{province}/"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    )
}

PROVINCES = {
    "GP": "gauteng",
    "WC": "western-cape",
    "KZN": "kwazulu-natal",
    "EC": "eastern-cape",
    "LP": "limpopo",
    "MP": "mpumalanga",
    "NW": "north-west",
    "NC": "northern-cape",
    "FS": "free-state",
}

PROVINCE_LABELS = {
    "GP": "Gauteng",
    "WC": "Western Cape",
    "KZN": "KwaZulu-Natal",
    "EC": "Eastern Cape",
    "LP": "Limpopo",
    "MP": "Mpumalanga",
    "NW": "North West",
    "NC": "Northern Cape",
    "FS": "Free State",
}


def parse_date(raw: str, year: int) -> str | None:
    """Try multiple date formats that appear on the site."""
    raw = raw.strip()
    for fmt in ("%d %B %Y", "%d %b %Y", "%B %d, %Y", "%d/%m/%Y"):
        try:
            return datetime.strptime(raw, fmt).strftime("%Y-%m-%d")
        except ValueError:
            continue
    return None


def scrape_province(province_code: str, year: int) -> list[dict]:
    slug = PROVINCES[province_code]
    url = BASE_URL.format(province=slug, year=year)
    print(f"Fetching {province_code}: {url}")

    try:
        response = requests.get(url, headers=HEADERS, timeout=10)
        response.raise_for_status()
    except (requests.HTTPError, requests.ConnectionError) as e:
        print(f"  WARNING: {e} — skipping {province_code}")
        print(f"  The source URL may be wrong. Check BASE_URL in this script.")
        return []

    soup = BeautifulSoup(response.text, "html.parser")

    breaks = []

    # The site uses a table with columns: Term/Holiday | From | To
    table = soup.find("table")
    if not table:
        print(f"  WARNING: No table found for {province_code} {year}")
        return []

    for row in table.find_all("tr")[1:]:  # skip header row
        cells = row.find_all("td")
        if len(cells) < 3:
            continue

        label = cells[0].get_text(strip=True)
        raw_start = cells[1].get_text(strip=True)
        raw_end = cells[2].get_text(strip=True)

        # Only capture school holiday breaks, not term start dates
        if "holiday" not in label.lower() and "break" not in label.lower() and "recess" not in label.lower():
            continue

        start = parse_date(raw_start, year)
        end = parse_date(raw_end, year)

        if not start or not end:
            print(f"  WARNING: Could not parse dates '{raw_start}' – '{raw_end}' — skipping")
            continue

        breaks.append({"start": start, "end": end, "label": label})
        print(f"  Found: {start} → {end} ({label})")

    return breaks


def to_js(year: int, province_data: dict[str, list[dict]]) -> str:
    lines = [
        f"// SA school holiday breaks {year} — auto-generated by scripts/scrape_school_holidays.py",
        f"// Source: https://www.schoolholidays.co.za/",
        "",
        f"export const SCHOOL_HOLIDAYS_{year} = {{",
    ]

    for code, breaks in province_data.items():
        label = PROVINCE_LABELS[code]
        lines.append(f"  {code}: {{")
        lines.append(f"    label: '{label}',")
        lines.append(f"    breaks: [")
        for b in breaks:
            lines.append(
                f"      {{ start: '{b['start']}', end: '{b['end']}', label: '{b['label']}' }},"
            )
        lines.append(f"    ],")
        lines.append(f"  }},")

    lines += [
        "}",
        "",
        f"export const PROVINCES = Object.entries(SCHOOL_HOLIDAYS_{year}).map(",
        "  ([code, { label }]) => ({ code, label })",
        ")",
        "",
        f"export function isSchoolHoliday(dateStr, provinceCode, year = {year}) {{",
        f"  const data = year === {year} ? SCHOOL_HOLIDAYS_{year} : null",
        "  if (!data) return false",
        "  const province = data[provinceCode]",
        "  if (!province) return false",
        "  const d = new Date(dateStr)",
        "  return province.breaks.some((b) => {",
        "    const start = new Date(b.start)",
        "    const end = new Date(b.end)",
        "    return d >= start && d <= end",
        "  })",
        "}",
        "",
        f"export function getSchoolBreakLabel(dateStr, provinceCode, year = {year}) {{",
        f"  const data = year === {year} ? SCHOOL_HOLIDAYS_{year} : null",
        "  if (!data) return null",
        "  const province = data[provinceCode]",
        "  if (!province) return null",
        "  const d = new Date(dateStr)",
        "  return province.breaks.find((b) => {",
        "    const start = new Date(b.start)",
        "    const end = new Date(b.end)",
        "    return d >= start && d <= end",
        "  })?.label ?? null",
        "}",
        "",
    ]

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Scrape SA school holidays by province")
    parser.add_argument("--year", type=int, default=datetime.now().year)
    parser.add_argument(
        "--provinces",
        nargs="+",
        default=list(PROVINCES.keys()),
        choices=list(PROVINCES.keys()),
        help="Province codes to scrape (default: all)",
    )
    parser.add_argument(
        "--output",
        default="web/src/data/schoolHolidays.js",
        help="Output JS file path",
    )
    args = parser.parse_args()

    province_data = {}
    for code in args.provinces:
        breaks = scrape_province(code, args.year)
        if breaks:
            province_data[code] = breaks

    if not province_data:
        print("\nERROR: No data scraped. The site structure may have changed.")
        print("Check the URLs manually and update BASE_URL in this script.")
        sys.exit(1)

    js_content = to_js(args.year, province_data)

    with open(args.output, "w") as f:
        f.write(js_content)

    print(f"\nDone — written to {args.output}")


if __name__ == "__main__":
    main()
